#! /bin/csh -f

source ../.setPDK.csh

set topcell      = croc_chip
set gdspath      = ./out/croc.gds
set netlist_path = ./out/croc.spi
set outdir       = ./lvs/out

if ( -e ${outdir} ) then
    echo "Removing existing directory: ${outdir}"
    rm -rf ${outdir}
endif

mkdir -p ${outdir}

python3 ${IHP_TECH}/klayout/tech/lvs/run_lvs.py \
 --layout=${gdspath} \
 --netlist=${netlist_path} \
 --topcell=${topcell} \
 --run_dir ${outdir}
